### ISSUE TITLE
Build broken?

### ISSUE THREAD

**Issue by Adafede** [SuLab/WikidataIntegrator#184]
Hi, 

It was a while I didn't use the tool but when I tried using it again it failed.
I tried re-installing from scratch without success:

```
git clone git@github.com:SuLab/WikidataIntegrator.git
Cloning into 'WikidataIntegrator'...
remote: Enumerating objects: 3766, done.
remote: Counting objects: 100% (548/548), done.
remote: Compressing objects: 100% (239/239), done.
remote: Total 3766 (delta 335), reused 451 (delta 288), pack-reused 3218
Receiving objects: 100% (3766/3766), 1.29 MiB | 3.56 MiB/s, done.
Resolving deltas: 100% (2487/2487), done.
```
```
(base) ➜  Git cd WikidataIntegrator 
(base) ➜  WikidataIntegrator git:(main) python3 setup.py install
running install
/opt/anaconda3/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/opt/anaconda3/lib/python3.8/site-packages/setuptools/command/easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
creating wikidataintegrator.egg-info
writing wikidataintegrator.egg-info/PKG-INFO
writing dependency_links to wikidataintegrator.egg-info/dependency_links.txt
writing entry points to wikidataintegrator.egg-info/entry_points.txt
writing requirements to wikidataintegrator.egg-info/requires.txt
writing top-level names to wikidataintegrator.egg-info/top_level.txt
writing manifest file 'wikidataintegrator.egg-info/SOURCES.txt'
reading manifest file 'wikidataintegrator.egg-info/SOURCES.txt'
adding license file 'LICENSE.txt'
writing manifest file 'wikidataintegrator.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.9-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/wikidataintegrator
copying wikidataintegrator/wdi_backoff.py -> build/lib/wikidataintegrator
copying wikidataintegrator/wdi_core.py -> build/lib/wikidataintegrator
copying wikidataintegrator/__init__.py -> build/lib/wikidataintegrator
copying wikidataintegrator/wdi_fastrun.py -> build/lib/wikidataintegrator
copying wikidataintegrator/wdi_rdf.py -> build/lib/wikidataintegrator
copying wikidataintegrator/wdi_login.py -> build/lib/wikidataintegrator
copying wikidataintegrator/wdi_config.py -> build/lib/wikidataintegrator
creating build/lib/wikidataintegrator/ref_handlers
copying wikidataintegrator/ref_handlers/update_release.py -> build/lib/wikidataintegrator/ref_handlers
copying wikidataintegrator/ref_handlers/update_retrieved_if_new_multiple_refs.py -> build/lib/wikidataintegrator/ref_handlers
copying wikidataintegrator/ref_handlers/strict_overwrite.py -> build/lib/wikidataintegrator/ref_handlers
copying wikidataintegrator/ref_handlers/__init__.py -> build/lib/wikidataintegrator/ref_handlers
copying wikidataintegrator/ref_handlers/test_update_retrieved_if_new.py -> build/lib/wikidataintegrator/ref_handlers
copying wikidataintegrator/ref_handlers/update_retrieved_if_new.py -> build/lib/wikidataintegrator/ref_handlers
creating build/lib/wikidataintegrator/tests
copying wikidataintegrator/tests/test_backoff.py -> build/lib/wikidataintegrator/tests
copying wikidataintegrator/tests/test_item_generator.py -> build/lib/wikidataintegrator/tests
copying wikidataintegrator/tests/test_wdi_login.py -> build/lib/wikidataintegrator/tests
copying wikidataintegrator/tests/__init__.py -> build/lib/wikidataintegrator/tests
copying wikidataintegrator/tests/test_item_creation.py -> build/lib/wikidataintegrator/tests
copying wikidataintegrator/tests/test_wd_search.py -> build/lib/wikidataintegrator/tests
copying wikidataintegrator/tests/test_wdi_helpers.py -> build/lib/wikidataintegrator/tests
copying wikidataintegrator/tests/tests.py -> build/lib/wikidataintegrator/tests
copying wikidataintegrator/tests/test_handle_refs.py -> build/lib/wikidataintegrator/tests
copying wikidataintegrator/tests/test_fastrun.py -> build/lib/wikidataintegrator/tests
creating build/lib/wikidataintegrator/wdi_helpers
copying wikidataintegrator/wdi_helpers/release.py -> build/lib/wikidataintegrator/wdi_helpers
copying wikidataintegrator/wdi_helpers/mapping_relation_helper.py -> build/lib/wikidataintegrator/wdi_helpers
copying wikidataintegrator/wdi_helpers/__init__.py -> build/lib/wikidataintegrator/wdi_helpers
copying wikidataintegrator/wdi_helpers/wikibase_helper.py -> build/lib/wikidataintegrator/wdi_helpers
copying wikidataintegrator/wdi_helpers/publication.py -> build/lib/wikidataintegrator/wdi_helpers
creating build/bdist.macosx-10.9-x86_64
creating build/bdist.macosx-10.9-x86_64/egg
creating build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator
copying build/lib/wikidataintegrator/wdi_backoff.py -> build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator
copying build/lib/wikidataintegrator/wdi_core.py -> build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator
creating build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/ref_handlers
copying build/lib/wikidataintegrator/ref_handlers/update_release.py -> build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/ref_handlers
copying build/lib/wikidataintegrator/ref_handlers/update_retrieved_if_new_multiple_refs.py -> build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/ref_handlers
copying build/lib/wikidataintegrator/ref_handlers/strict_overwrite.py -> build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/ref_handlers
copying build/lib/wikidataintegrator/ref_handlers/__init__.py -> build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/ref_handlers
copying build/lib/wikidataintegrator/ref_handlers/test_update_retrieved_if_new.py -> build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/ref_handlers
copying build/lib/wikidataintegrator/ref_handlers/update_retrieved_if_new.py -> build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/ref_handlers
creating build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/tests
copying build/lib/wikidataintegrator/tests/test_backoff.py -> build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/tests
copying build/lib/wikidataintegrator/tests/test_item_generator.py -> build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/tests
copying build/lib/wikidataintegrator/tests/test_wdi_login.py -> build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/tests
copying build/lib/wikidataintegrator/tests/__init__.py -> build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/tests
copying build/lib/wikidataintegrator/tests/test_item_creation.py -> build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/tests
copying build/lib/wikidataintegrator/tests/test_wd_search.py -> build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/tests
copying build/lib/wikidataintegrator/tests/test_wdi_helpers.py -> build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/tests
copying build/lib/wikidataintegrator/tests/tests.py -> build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/tests
copying build/lib/wikidataintegrator/tests/test_handle_refs.py -> build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/tests
copying build/lib/wikidataintegrator/tests/test_fastrun.py -> build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/tests
copying build/lib/wikidataintegrator/__init__.py -> build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator
creating build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/wdi_helpers
copying build/lib/wikidataintegrator/wdi_helpers/release.py -> build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/wdi_helpers
copying build/lib/wikidataintegrator/wdi_helpers/mapping_relation_helper.py -> build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/wdi_helpers
copying build/lib/wikidataintegrator/wdi_helpers/__init__.py -> build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/wdi_helpers
copying build/lib/wikidataintegrator/wdi_helpers/wikibase_helper.py -> build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/wdi_helpers
copying build/lib/wikidataintegrator/wdi_helpers/publication.py -> build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/wdi_helpers
copying build/lib/wikidataintegrator/wdi_fastrun.py -> build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator
copying build/lib/wikidataintegrator/wdi_rdf.py -> build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator
copying build/lib/wikidataintegrator/wdi_login.py -> build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator
copying build/lib/wikidataintegrator/wdi_config.py -> build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator
byte-compiling build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/wdi_backoff.py to wdi_backoff.cpython-38.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/wdi_core.py to wdi_core.cpython-38.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/ref_handlers/update_release.py to update_release.cpython-38.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/ref_handlers/update_retrieved_if_new_multiple_refs.py to update_retrieved_if_new_multiple_refs.cpython-38.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/ref_handlers/strict_overwrite.py to strict_overwrite.cpython-38.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/ref_handlers/__init__.py to __init__.cpython-38.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/ref_handlers/test_update_retrieved_if_new.py to test_update_retrieved_if_new.cpython-38.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/ref_handlers/update_retrieved_if_new.py to update_retrieved_if_new.cpython-38.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/tests/test_backoff.py to test_backoff.cpython-38.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/tests/test_item_generator.py to test_item_generator.cpython-38.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/tests/test_wdi_login.py to test_wdi_login.cpython-38.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/tests/__init__.py to __init__.cpython-38.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/tests/test_item_creation.py to test_item_creation.cpython-38.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/tests/test_wd_search.py to test_wd_search.cpython-38.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/tests/test_wdi_helpers.py to test_wdi_helpers.cpython-38.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/tests/tests.py to tests.cpython-38.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/tests/test_handle_refs.py to test_handle_refs.cpython-38.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/tests/test_fastrun.py to test_fastrun.cpython-38.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/__init__.py to __init__.cpython-38.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/wdi_helpers/release.py to release.cpython-38.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/wdi_helpers/mapping_relation_helper.py to mapping_relation_helper.cpython-38.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/wdi_helpers/__init__.py to __init__.cpython-38.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/wdi_helpers/wikibase_helper.py to wikibase_helper.cpython-38.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/wdi_helpers/publication.py to publication.cpython-38.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/wdi_fastrun.py to wdi_fastrun.cpython-38.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/wdi_rdf.py to wdi_rdf.cpython-38.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/wdi_login.py to wdi_login.cpython-38.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/wikidataintegrator/wdi_config.py to wdi_config.cpython-38.pyc
creating build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying wikidataintegrator.egg-info/PKG-INFO -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying wikidataintegrator.egg-info/SOURCES.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying wikidataintegrator.egg-info/dependency_links.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying wikidataintegrator.egg-info/entry_points.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying wikidataintegrator.egg-info/requires.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying wikidataintegrator.egg-info/top_level.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/wikidataintegrator-0.9.19-py3.8.egg' and adding 'build/bdist.macosx-10.9-x86_64/egg' to it
removing 'build/bdist.macosx-10.9-x86_64/egg' (and everything under it)
Processing wikidataintegrator-0.9.19-py3.8.egg
Copying wikidataintegrator-0.9.19-py3.8.egg to /opt/anaconda3/lib/python3.8/site-packages
Adding wikidataintegrator 0.9.19 to easy-install.pth file
Installing wikidataintegrator-publication script to /opt/anaconda3/bin

Installed /opt/anaconda3/lib/python3.8/site-packages/wikidataintegrator-0.9.19-py3.8.egg
Processing dependencies for wikidataintegrator==0.9.19
Searching for shexer==1.4.0
Best match: shexer 1.4.0
Processing shexer-1.4.0-py3.8.egg
shexer 1.4.0 is already the active version in easy-install.pth

Using /opt/anaconda3/lib/python3.8/site-packages/shexer-1.4.0-py3.8.egg
Searching for backoff==1.10.0
Best match: backoff 1.10.0
Processing backoff-1.10.0-py3.8.egg
backoff 1.10.0 is already the active version in easy-install.pth

Using /opt/anaconda3/lib/python3.8/site-packages/backoff-1.10.0-py3.8.egg
Searching for PyShEx==0.7.20
Best match: PyShEx 0.7.20
Processing PyShEx-0.7.20-py3.8.egg
PyShEx 0.7.20 is already the active version in easy-install.pth
Installing shexeval script to /opt/anaconda3/bin

Using /opt/anaconda3/lib/python3.8/site-packages/PyShEx-0.7.20-py3.8.egg
Searching for jsonasobj==2.0.2.dev4
Best match: jsonasobj 2.0.2.dev4
Processing jsonasobj-2.0.2.dev4-py3.8.egg
jsonasobj 2.0.2.dev4 is already the active version in easy-install.pth

Using /opt/anaconda3/lib/python3.8/site-packages/jsonasobj-2.0.2.dev4-py3.8.egg
Searching for oauthlib==3.1.1
Best match: oauthlib 3.1.1
Processing oauthlib-3.1.1-py3.8.egg
oauthlib 3.1.1 is already the active version in easy-install.pth

Using /opt/anaconda3/lib/python3.8/site-packages/oauthlib-3.1.1-py3.8.egg
Searching for mwoauth==0.3.7
Best match: mwoauth 0.3.7
Processing mwoauth-0.3.7-py3.8.egg
mwoauth 0.3.7 is already the active version in easy-install.pth

Using /opt/anaconda3/lib/python3.8/site-packages/mwoauth-0.3.7-py3.8.egg
Searching for tqdm==4.62.3
Best match: tqdm 4.62.3
Adding tqdm 4.62.3 to easy-install.pth file
Installing tqdm script to /opt/anaconda3/bin

Using /opt/anaconda3/lib/python3.8/site-packages
Searching for pandas==1.3.4
Best match: pandas 1.3.4
Processing pandas-1.3.4-py3.8-macosx-10.9-x86_64.egg
pandas 1.3.4 is already the active version in easy-install.pth

Using /opt/anaconda3/lib/python3.8/site-packages/pandas-1.3.4-py3.8-macosx-10.9-x86_64.egg
Searching for simplejson==3.17.2
Best match: simplejson 3.17.2
Processing simplejson-3.17.2-py3.8-macosx-10.9-x86_64.egg
simplejson 3.17.2 is already the active version in easy-install.pth

Using /opt/anaconda3/lib/python3.8/site-packages/simplejson-3.17.2-py3.8-macosx-10.9-x86_64.egg
Searching for python-dateutil==2.8.2
Best match: python-dateutil 2.8.2
Processing python_dateutil-2.8.2-py3.8.egg
python-dateutil 2.8.2 is already the active version in easy-install.pth

Using /opt/anaconda3/lib/python3.8/site-packages/python_dateutil-2.8.2-py3.8.egg
Searching for requests==2.26.0
Best match: requests 2.26.0
Processing requests-2.26.0-py3.8.egg
requests 2.26.0 is already the active version in easy-install.pth

Using /opt/anaconda3/lib/python3.8/site-packages/requests-2.26.0-py3.8.egg
Searching for wlighter==1.0.1
Best match: wlighter 1.0.1
Adding wlighter 1.0.1 to easy-install.pth file

Using /opt/anaconda3/lib/python3.8/site-packages
Searching for rdflib-jsonld==0.5.0
Best match: rdflib-jsonld 0.5.0
Processing rdflib_jsonld-0.5.0-py3.8.egg
rdflib-jsonld 0.5.0 is already the active version in easy-install.pth

Using /opt/anaconda3/lib/python3.8/site-packages/rdflib_jsonld-0.5.0-py3.8.egg
Searching for SPARQLWrapper==1.8.5
Best match: SPARQLWrapper 1.8.5
Processing SPARQLWrapper-1.8.5-py3.8.egg
SPARQLWrapper 1.8.5 is already the active version in easy-install.pth

Using /opt/anaconda3/lib/python3.8/site-packages/SPARQLWrapper-1.8.5-py3.8.egg
Searching for rdflib==5.0.0
Best match: rdflib 5.0.0
Processing rdflib-5.0.0-py3.8.egg
rdflib 5.0.0 is already the active version in easy-install.pth
Installing csv2rdf script to /opt/anaconda3/bin
Installing rdf2dot script to /opt/anaconda3/bin
Installing rdfgraphisomorphism script to /opt/anaconda3/bin
Installing rdfpipe script to /opt/anaconda3/bin
Installing rdfs2dot script to /opt/anaconda3/bin

Using /opt/anaconda3/lib/python3.8/site-packages/rdflib-5.0.0-py3.8.egg
Searching for Flask-Cors==3.0.10
Best match: Flask-Cors 3.0.10
Adding Flask-Cors 3.0.10 to easy-install.pth file

Using /opt/anaconda3/lib/python3.8/site-packages
Searching for Flask==2.0.2
Best match: Flask 2.0.2
Adding Flask 2.0.2 to easy-install.pth file
Installing flask script to /opt/anaconda3/bin

Using /opt/anaconda3/lib/python3.8/site-packages
Searching for urllib3==1.26.7
Best match: urllib3 1.26.7
Adding urllib3 1.26.7 to easy-install.pth file

Using /opt/anaconda3/lib/python3.8/site-packages
Searching for sparqlslurper==0.4.1
Best match: sparqlslurper 0.4.1
Processing sparqlslurper-0.4.1-py3.8.egg
sparqlslurper 0.4.1 is already the active version in easy-install.pth

Using /opt/anaconda3/lib/python3.8/site-packages/sparqlslurper-0.4.1-py3.8.egg
Searching for ShExJSG==0.7.1
Best match: ShExJSG 0.7.1
Processing ShExJSG-0.7.1-py3.8.egg
ShExJSG 0.7.1 is already the active version in easy-install.pth

Using /opt/anaconda3/lib/python3.8/site-packages/ShExJSG-0.7.1-py3.8.egg
Searching for PyShExC==0.8.3
Best match: PyShExC 0.8.3
Processing PyShExC-0.8.3-py3.8.egg
PyShExC 0.8.3 is already the active version in easy-install.pth

Using /opt/anaconda3/lib/python3.8/site-packages/PyShExC-0.8.3-py3.8.egg
Searching for CFGraph==0.2.1
Best match: CFGraph 0.2.1
Processing CFGraph-0.2.1-py3.8.egg
CFGraph 0.2.1 is already the active version in easy-install.pth

Using /opt/anaconda3/lib/python3.8/site-packages/CFGraph-0.2.1-py3.8.egg
Searching for hbreader==0.9.1
Best match: hbreader 0.9.1
Processing hbreader-0.9.1-py3.8.egg
hbreader 0.9.1 is already the active version in easy-install.pth

Using /opt/anaconda3/lib/python3.8/site-packages/hbreader-0.9.1-py3.8.egg
Searching for six==1.16.0
Best match: six 1.16.0
Adding six 1.16.0 to easy-install.pth file

Using /opt/anaconda3/lib/python3.8/site-packages
Searching for requests-oauthlib==1.3.0
Best match: requests-oauthlib 1.3.0
Processing requests_oauthlib-1.3.0-py3.8.egg
requests-oauthlib 1.3.0 is already the active version in easy-install.pth

Using /opt/anaconda3/lib/python3.8/site-packages/requests_oauthlib-1.3.0-py3.8.egg
Searching for PyJWT==1.7.1
Best match: PyJWT 1.7.1
Processing PyJWT-1.7.1-py3.8.egg
PyJWT 1.7.1 is already the active version in easy-install.pth
Installing pyjwt script to /opt/anaconda3/bin

Using /opt/anaconda3/lib/python3.8/site-packages/PyJWT-1.7.1-py3.8.egg
Searching for pytz==2021.3
Best match: pytz 2021.3
Adding pytz 2021.3 to easy-install.pth file

Using /opt/anaconda3/lib/python3.8/site-packages
Searching for numpy==1.21.3
Best match: numpy 1.21.3
Adding numpy 1.21.3 to easy-install.pth file
Installing f2py script to /opt/anaconda3/bin
Installing f2py3 script to /opt/anaconda3/bin
Installing f2py3.8 script to /opt/anaconda3/bin

Using /opt/anaconda3/lib/python3.8/site-packages
Searching for idna==3.3
Best match: idna 3.3
Adding idna 3.3 to easy-install.pth file

Using /opt/anaconda3/lib/python3.8/site-packages
Searching for charset-normalizer==2.0.7
Best match: charset-normalizer 2.0.7
Adding charset-normalizer 2.0.7 to easy-install.pth file
Installing normalizer script to /opt/anaconda3/bin

Using /opt/anaconda3/lib/python3.8/site-packages
Searching for certifi==2021.10.8
Best match: certifi 2021.10.8
Adding certifi 2021.10.8 to easy-install.pth file

Using /opt/anaconda3/lib/python3.8/site-packages
Searching for pyparsing==3.0.6
Best match: pyparsing 3.0.6
Adding pyparsing 3.0.6 to easy-install.pth file

Using /opt/anaconda3/lib/python3.8/site-packages
Searching for isodate==0.6.0
Best match: isodate 0.6.0
Processing isodate-0.6.0-py3.8.egg
isodate 0.6.0 is already the active version in easy-install.pth

Using /opt/anaconda3/lib/python3.8/site-packages/isodate-0.6.0-py3.8.egg
Searching for Werkzeug==2.0.2
Best match: Werkzeug 2.0.2
Adding Werkzeug 2.0.2 to easy-install.pth file

Using /opt/anaconda3/lib/python3.8/site-packages
Searching for itsdangerous==2.0.1
Best match: itsdangerous 2.0.1
Adding itsdangerous 2.0.1 to easy-install.pth file

Using /opt/anaconda3/lib/python3.8/site-packages
Searching for Jinja2==3.0.3
Best match: Jinja2 3.0.3
Adding Jinja2 3.0.3 to easy-install.pth file

Using /opt/anaconda3/lib/python3.8/site-packages
Searching for click==8.0.3
Best match: click 8.0.3
Adding click 8.0.3 to easy-install.pth file

Using /opt/anaconda3/lib/python3.8/site-packages
Searching for PyJSG==0.11.6
Best match: PyJSG 0.11.6
Processing PyJSG-0.11.6-py3.8.egg
PyJSG 0.11.6 is already the active version in easy-install.pth
Installing generate_parser script to /opt/anaconda3/bin

Using /opt/anaconda3/lib/python3.8/site-packages/PyJSG-0.11.6-py3.8.egg
Searching for antlr4-python3-runtime==4.9.2
Best match: antlr4-python3-runtime 4.9.2
Adding antlr4-python3-runtime 4.9.2 to easy-install.pth file

Using /opt/anaconda3/lib/python3.8/site-packages
Searching for MarkupSafe==2.0.1
Best match: MarkupSafe 2.0.1
Adding MarkupSafe 2.0.1 to easy-install.pth file

Using /opt/anaconda3/lib/python3.8/site-packages
Finished processing dependencies for wikidataintegrator==0.9.19
```

```
(base) ➜  WikidataIntegrator git:(main) wikidataintegrator-publication --idtype doi 10.3389/fgene.2021.768979
Traceback (most recent call last):
  File "/opt/anaconda3/bin/wikidataintegrator-publication", line 33, in <module>
    sys.exit(load_entry_point('wikidataintegrator==0.9.19', 'console_scripts', 'wikidataintegrator-publication')())
  File "/opt/anaconda3/bin/wikidataintegrator-publication", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/opt/anaconda3/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/opt/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/opt/anaconda3/lib/python3.8/site-packages/wikidataintegrator-0.9.19-py3.8.egg/wikidataintegrator/__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/opt/anaconda3/lib/python3.8/site-packages/wikidataintegrator-0.9.19-py3.8.egg/wikidataintegrator/wdi_core.py", line 16, in <module>
  File "/opt/anaconda3/lib/python3.8/site-packages/shexer-1.4.0-py3.8.egg/shexer/shaper.py", line 5, in <module>
    from shexer.utils.factories.class_profiler_factory import get_class_profiler
  File "/opt/anaconda3/lib/python3.8/site-packages/shexer-1.4.0-py3.8.egg/shexer/utils/factories/class_profiler_factory.py", line 1, in <module>
    from shexer.utils.factories.triple_yielders_factory import get_triple_yielder
  File "/opt/anaconda3/lib/python3.8/site-packages/shexer-1.4.0-py3.8.egg/shexer/utils/factories/triple_yielders_factory.py", line 11, in <module>
    from shexer.utils.factories.shape_map_parser_factory import get_shape_map_parser
  File "/opt/anaconda3/lib/python3.8/site-packages/shexer-1.4.0-py3.8.egg/shexer/utils/factories/shape_map_parser_factory.py", line 2, in <module>
    from shexer.io.shape_map.shape_map_parser import JsonShapeMapParser, FixedShapeMapParser
  File "/opt/anaconda3/lib/python3.8/site-packages/shexer-1.4.0-py3.8.egg/shexer/io/shape_map/shape_map_parser.py", line 3, in <module>
    from shexer.io.shape_map.node_selector.node_selector_parser import NodeSelectorParser
  File "/opt/anaconda3/lib/python3.8/site-packages/shexer-1.4.0-py3.8.egg/shexer/io/shape_map/node_selector/node_selector_parser.py", line 4, in <module>
    from rdflib.plugins import sparql
  File "/opt/anaconda3/lib/python3.8/site-packages/rdflib-5.0.0-py3.8.egg/rdflib/plugins/sparql/__init__.py", line 33, in <module>
    from . import parser
  File "/opt/anaconda3/lib/python3.8/site-packages/rdflib-5.0.0-py3.8.egg/rdflib/plugins/sparql/parser.py", line 184, in <module>
    Param('prefix', PN_PREFIX)) + Suppress(':').leaveWhitespace()
  File "/opt/anaconda3/lib/python3.8/site-packages/rdflib-5.0.0-py3.8.egg/rdflib/plugins/sparql/parserutils.py", line 114, in __init__
    self.name = name
AttributeError: can't set attribute
```

Can't really see where the problem is. 
Tried re-installling many dependencies with pip instead of conda, again, unsuccessful...

**Comment by andrawaag** [comment]
Thanks for raising the issue. The issue is due to an update in rdflib which created a conflict with an older version within another dependency of rdflib. We are investigating the bug and we are working towards a fix.
This issue is that the issue does not emerge in all python versions.

**Comment by Adafede** [comment]
Thank you for your reply, looks like a nightmare to fix...

As you mentioned the issue is not emerging in all python versions, could you give a python version working fine as a temporary workaround?

**Comment by andrawaag** [comment]
So far it seems to work in python 3.8+. Running locally (3.9) I have no issues, nor does it when used in Wikimedia's paws (jupyterhub) https://hub.paws.wmcloud.org/

**Comment by andrawaag** [comment]
I just noticed that in your error dump it states that you are using 3.8. So my previous answer is not helping. Paws still works though. Maybe because it is using a cached version of the failing import. Anyway, investigation continues.

**Comment by Adafede** [comment]
Just tried on PAWS (thanks, did not use it before):

still getting 
```
Traceback (most recent call last):
  File "/srv/paws/bin/wikidataintegrator-publication", line 5, in <module>
    from wikidataintegrator.wdi_helpers.publication import main
  File "/srv/paws/lib/python3.8/site-packages/wikidataintegrator/__init__.py", line 3, in <module>
    import wikidataintegrator.wdi_core
  File "/srv/paws/lib/python3.8/site-packages/wikidataintegrator/wdi_core.py", line 14, in <module>
    from pyshex import ShExEvaluator
  File "/srv/paws/lib/python3.8/site-packages/pyshex/__init__.py", line 1, in <module>
    from pyshex.prefixlib import PrefixLibrary, standard_prefixes, known_prefixes
  File "/srv/paws/lib/python3.8/site-packages/pyshex/prefixlib.py", line 4, in <module>
    from pyshexc.parser_impl.generate_shexj import load_shex_file
  File "/srv/paws/lib/python3.8/site-packages/pyshexc/parser_impl/generate_shexj.py", line 9, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'
```

**Comment by andrawaag** [comment]
Indeed I forget to mention this. This bug is probably related since it emerged about the same time as the one reported here. 
However, a quick fix here is to add the line 
`!pip install chardet`
in one of the first cells. I added in the first line where I also import the wikidata integrator. 
I have added it to the requirements.txt file for now, but I will only release that once I found the reason for this issue. Fixing that might make that line redundant.

**Comment by turoger** [comment]
Hi, I had the same issue last week and this is how I approached it. I raised the issue with RDF last [week](https://github.com/RDFLib/rdflib/issues/1465).

**Comment by turoger** [comment]
So  Maxime Lefrançois  [responded](https://github.com/RDFLib/rdflib/issues/1465#issuecomment-977966462) and referenced [rdflib issue 1204](https://github.com/RDFLib/rdflib/issues/1204). I have tested it out and so far it works for me.  Just need to set the requirements `pyparsing==2.4.7`.

**Comment by Adafede** [comment]
> So Maxime Lefrançois [responded](https://github.com/RDFLib/rdflib/issues/1465#issuecomment-977966462) and referenced [rdflib issue 1204](https://github.com/RDFLib/rdflib/issues/1204). I have tested it out on `Python 3.8.5` and so far it works for me. Just need to set the requirements `pyparsing==2.4.7`.

Confirm this fixes the issue

**Comment by andrawaag** [comment]
Package release of WDI 0.9.20 confirmed that adding pyparsing==2.4.7 to the requirements.txt did not solve this yet. 
Separately installing it with pip as mentioned above does.
