### ISSUE TITLE
Error when parsing a particular item

### ISSUE THREAD

**Issue by despens** [SuLab/WikidataIntegrator#192]
Wikidata Integrator has issues parsing the json of a particular item in my Wikibase.

Any idea what the issue could be?

```pytb
Traceback (most recent call last):
  File "./016_exchange-variants-artifacts.py", line 39, in <module>
    v1 = wdi_core.WDItemEngine(wd_item_id=qid,
  File "/usr/local/lib/python3.8/dist-packages/wikidataintegrator/wdi_core.py", line 191, in __init__
    self.init_data_load()
  File "/usr/local/lib/python3.8/dist-packages/wikidataintegrator/wdi_core.py", line 237, in init_data_load
    self.wd_json_representation = self.get_wd_entity()
  File "/usr/local/lib/python3.8/dist-packages/wikidataintegrator/wdi_core.py", line 298, in get_wd_entity
    return self.parse_wd_json(wd_json=json_data['entities'][self.wd_item_id])
  File "/usr/local/lib/python3.8/dist-packages/wikidataintegrator/wdi_core.py", line 316, in parse_wd_json
    data_type = [x for x in WDBaseDataType.__subclasses__() if x.DTYPE == z['mainsnak']['datatype']][0]
IndexError: list index out of range
```

<details>
<summary>JSON representation of the item in question</summary>

```json
{
    "entities":
    {
        "Q4669":
        {
            "pageid": 14977,
            "ns": 120,
            "title": "Item:Q4669",
            "lastrevid": 169893,
            "modified": "2022-03-21T10:44:58Z",
            "type": "item",
            "id": "Q4669",
            "labels":
            {
                "en":
                {
                    "language": "en",
                    "value": "Beautiful Frog"
                }
            },
            "descriptions":
            {
                "en":
                {
                    "language": "en",
                    "value": "artwork by Porpentine Charity Heartscape"
                }
            },
            "aliases":
            {
                "en":
                [
                    {
                        "language": "en",
                        "value": "frog game"
                    }
                ]
            },
            "claims":
            {
                "P3":
                [
                    {
                        "mainsnak":
                        {
                            "snaktype": "value",
                            "property": "P3",
                            "datavalue":
                            {
                                "value":
                                {
                                    "entity-type": "item",
                                    "numeric-id": 5,
                                    "id": "Q5"
                                },
                                "type": "wikibase-entityid"
                            },
                            "datatype": "wikibase-item"
                        },
                        "type": "statement",
                        "id": "Q4669$de5fd51a-45ab-e549-b434-3ed0bf609e86",
                        "rank": "normal"
                    }
                ],
                "P29":
                [
                    {
                        "mainsnak":
                        {
                            "snaktype": "value",
                            "property": "P29",
                            "datavalue":
                            {
                                "value":
                                {
                                    "entity-type": "item",
                                    "numeric-id": 4668,
                                    "id": "Q4668"
                                },
                                "type": "wikibase-entityid"
                            },
                            "datatype": "wikibase-item"
                        },
                        "type": "statement",
                        "id": "Q4669$a3b2ebaa-4eea-e0fe-ea28-bab3d87419b0",
                        "rank": "normal"
                    }
                ],
                "P26":
                [
                    {
                        "mainsnak":
                        {
                            "snaktype": "value",
                            "property": "P26",
                            "datavalue":
                            {
                                "value":
                                {
                                    "time": "+2015-00-00T00:00:00Z",
                                    "timezone": 0,
                                    "before": 0,
                                    "after": 0,
                                    "precision": 9,
                                    "calendarmodel": "http://www.wikidata.org/entity/Q1985727"
                                },
                                "type": "time"
                            },
                            "datatype": "time"
                        },
                        "type": "statement",
                        "id": "Q4669$07b8da11-4389-cd85-5130-e3510fda7dd2",
                        "rank": "normal"
                    }
                ],
                "P49":
                [
                    {
                        "mainsnak":
                        {
                            "snaktype": "value",
                            "property": "P49",
                            "datavalue":
                            {
                                "value": "beautiful-frog",
                                "type": "string"
                            },
                            "datatype": "string"
                        },
                        "type": "statement",
                        "id": "Q4669$4e4d75c9-4abb-42b8-b9e3-ba43abba3f9c",
                        "rank": "normal"
                    }
                ],
                "P45":
                [
                    {
                        "mainsnak":
                        {
                            "snaktype": "value",
                            "property": "P45",
                            "datavalue":
                            {
                                "value":
                                {
                                    "entity-type": "item",
                                    "numeric-id": 4670,
                                    "id": "Q4670"
                                },
                                "type": "wikibase-entityid"
                            },
                            "datatype": "wikibase-item"
                        },
                        "type": "statement",
                        "id": "Q4669$983d9dce-4001-0c75-39f4-ed088aef7828",
                        "rank": "normal"
                    },
                    {
                        "mainsnak":
                        {
                            "snaktype": "value",
                            "property": "P45",
                            "datavalue":
                            {
                                "value":
                                {
                                    "entity-type": "item",
                                    "numeric-id": 9286,
                                    "id": "Q9286"
                                },
                                "type": "wikibase-entityid"
                            },
                            "datatype": "wikibase-item"
                        },
                        "type": "statement",
                        "id": "Q4669$30AF1ED3-5185-4B2A-8BC9-A037BBCB2F13",
                        "rank": "normal"
                    }
                ],
                "P85":
                [
                    {
                        "mainsnak":
                        {
                            "snaktype": "value",
                            "property": "P85",
                            "datavalue":
                            {
                                "value":
                                {
                                    "time": "+2015-11-01T00:00:00Z",
                                    "timezone": 0,
                                    "before": 0,
                                    "after": 0,
                                    "precision": 11,
                                    "calendarmodel": "http://www.wikidata.org/entity/Q1985727"
                                },
                                "type": "time"
                            },
                            "datatype": "time"
                        },
                        "type": "statement",
                        "id": "Q4669$f1757272-4533-98e1-a742-86fb90dd44d8",
                        "rank": "normal"
                    }
                ],
                "P123":
                [
                    {
                        "mainsnak":
                        {
                            "snaktype": "value",
                            "property": "P123",
                            "datavalue":
                            {
                                "value":
                                {
                                    "entity-type": "item",
                                    "numeric-id": 7228,
                                    "id": "Q7228"
                                },
                                "type": "wikibase-entityid"
                            },
                            "datatype": "wikibase-item"
                        },
                        "type": "statement",
                        "id": "Q4669$14C8D349-70AA-40BC-90FD-D54417FF4EBD",
                        "rank": "normal"
                    }
                ],
                "P126":
                [
                    {
                        "mainsnak":
                        {
                            "snaktype": "value",
                            "property": "P126",
                            "datavalue":
                            {
                                "value": "Beautiful-Frog-screenshot.png",
                                "type": "string"
                            },
                            "datatype": "localMedia"
                        },
                        "type": "statement",
                        "id": "Q4669$748A7A52-CFFB-4919-BF4A-AD7B18952931",
                        "rank": "deprecated"
                    },
                    {
                        "mainsnak":
                        {
                            "snaktype": "value",
                            "property": "P126",
                            "datavalue":
                            {
                                "value": "beautiful frog epiphany3.36 linux.png",
                                "type": "string"
                            },
                            "datatype": "localMedia"
                        },
                        "type": "statement",
                        "id": "Q4669$433b5b97-4204-49f6-d505-2232e31c788c",
                        "rank": "normal"
                    }
                ],
                "P131":
                [
                    {
                        "mainsnak":
                        {
                            "snaktype": "value",
                            "property": "P131",
                            "datavalue":
                            {
                                "value":
                                {
                                    "text": "frog game",
                                    "language": "en"
                                },
                                "type": "monolingualtext"
                            },
                            "datatype": "monolingualtext"
                        },
                        "type": "statement",
                        "id": "Q4669$90e7c19d-47a6-8785-3124-cb440e47696e",
                        "rank": "normal"
                    }
                ],
                "P134":
                [
                    {
                        "mainsnak":
                        {
                            "snaktype": "value",
                            "property": "P134",
                            "datavalue":
                            {
                                "value": "beautiful frog detail.png",
                                "type": "string"
                            },
                            "datatype": "localMedia"
                        },
                        "type": "statement",
                        "id": "Q4669$45a81486-488b-fd9b-307c-2e350a4f66b6",
                        "rank": "normal"
                    }
                ]
            },
            "sitelinks":
            {
                "artbase":
                {
                    "site": "artbase",
                    "title": "Q4669",
                    "badges":
                    [],
                    "url": "https://artbase.rhizome.org/wiki/Q4669"
                }
            }
        }
    }
}
```

</details>

**Comment by despens** [comment]
Invalid bug report.
