### ISSUE TITLE
Issue testing install

### ISSUE THREAD

**Issue by Superraptor** [SuLab/WikidataIntegrator#205]
Hello! Trying to run the basic test script, i.e.:

```
from wikidataintegrator import wdi_core

my_first_wikidata_item = wdi_core.WDItemEngine(wd_item_id='Q5')
```

This results in the following traceback:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\[USERNAME]\anaconda3\envs\wbsync_test\Lib\site-packages\wikidataintegrator\wdi_core.py", line 461, in __init__
    self.init_data_load()
  File "C:\Users\[USERNAME]\anaconda3\envs\wbsync_test\Lib\site-packages\wikidataintegrator\wdi_core.py", line 505, in init_data_load
    self.wd_json_representation = self.get_wd_entity()
                                  ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[USERNAME]\anaconda3\envs\wbsync_test\Lib\site-packages\wikidataintegrator\wdi_core.py", line 600, in get_wd_entity
    return self.parse_wd_json(wd_json=json_data['entities'][self.wd_item_id])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[USERNAME]\anaconda3\envs\wbsync_test\Lib\site-packages\wikidataintegrator\wdi_core.py", line 620, in parse_wd_json
    data_type = [x for x in WDBaseDataType.__subclasses__() if x.DTYPE == z['mainsnak']['datatype']][0]
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

I'm brand new so not exactly sure how to debug; any help appreciated!

**Comment by Superraptor** [comment]
(If it helps I'm using version `wikidataintegrator==0.9.30` and Python 3.11.9)

**Comment by DLu** [comment]
I have replicated this, same version number

**Comment by LeMyst** [comment]
WikidataIntegrator doesn't support EntitySchema
Should not be an issue if you don't have an EntitySchema referenced in your entity.

**Comment by egonw** [comment]
> Should not be an issue if you don't have an EntitySchema referenced in your entity.

It is a problem, because even if you do not use it, the above exception is thrown.

**Comment by LeMyst** [comment]
> > Should not be an issue if you don't have an EntitySchema referenced in your entity.
> 
> It is a problem, because even if you do not use it, the above exception is thrown.

Do you have an Entity example ?

**Comment by egonw** [comment]
> Do you have an Entity example ?

I am not sure what you mean. The error message has shown up for me with the JavaScript wikibase client code. Clients seem to need to have the property value type encoded, like on: https://github.com/SuLab/WikidataIntegrator/blob/505d58d7c1d530c79f00bb1ad6b4500fd303efc4/wikidataintegrator/wdi_config.py#L69

Or in your fork at: https://github.com/LeMyst/WikibaseIntegrator/blob/221baa867304203b5892ecd8a27d660e15ee9b4c/wikibaseintegrator/wbi_enums.py#L21

My expectation is that this problem is solved when `entity-schema` has been added to the code.
