### ISSUE TITLE
PubmedItem helper fails if there it has no PMID

### ISSUE THREAD

**Issue by tarrow** [SuLab/WikidataIntegrator#41]
Some items in PMC don't have a PMID but do still have a PMCID. This causes the error below that assumes every response will have a PMID.

Perhaps items of this type should really be handled by a differently named function but since they're quite an edge case it's probably best to just work around it here.

An example article is PMC3425984.

```
(venv-fatameh2) (precise)tom@localhost:~/git/tool-fatameh$ python
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from wikidataintegrator import wdi_core, wdi_login, wdi_helpers
>>> item=wdi_helpers.PubmedItem('PMC3425984', id_type='PMC')
>>> item.get_
item.get_article_info(  item.get_metadata(      item.get_or_create(     
>>> item.get_metadata()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tom/venv-fatameh2/src/wikidataintegrator/wikidataintegrator/wdi_helpers.py", line 249, in get_metadata
    self.meta['pmid'] = self.article['pmid']
KeyError: 'pmid'
```

**Comment by stuppie** [comment]
https://github.com/SuLab/WikidataIntegrator/commit/046ce33f33c505110bfd8dddb6edb461078cd21f
