### ISSUE TITLE
Problem with decoder

### ISSUE THREAD

**Issue by skeating** [SuLab/WikidataIntegrator#43]
I was getting a problem with code that has previously worked for me.

I then tried the example code you give to check correct installation and I get the same problem

>>> my_first_wikidata_item = wdi_core.WDItemEngine(wd_item_id='Q5')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python64\Python34\lib\site-packages\wikidataintegrator\wdi_core.py",
line 132, in __init__
    WDItemEngine._init_ref_system()
  File "C:\Python64\Python34\lib\site-packages\wikidataintegrator\wdi_core.py",
line 1095, in _init_ref_system
    for x in WDItemEngine.execute_sparql_query(pmid_query)['results']['bindings'
]:
  File "C:\Python64\Python34\lib\site-packages\wikidataintegrator\backoff\backof
f.py", line 286, in retry
    ret = target(*args, **kwargs)
  File "C:\Python64\Python34\lib\site-packages\wikidataintegrator\wdi_core.py",
line 1016, in execute_sparql_query
    return json.loads(response.text)
  File "C:\Python64\Python34\lib\site-packages\simplejson\__init__.py", line 516
, in loads
    return _default_decoder.decode(s)
  File "C:\Python64\Python34\lib\site-packages\simplejson\decoder.py", line 374,
 in decode
    obj, end = self.raw_decode(s)
  File "C:\Python64\Python34\lib\site-packages\simplejson\decoder.py", line 404,
 in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Invalid control character '\n' at: line 1267
1119 column 81 (char 293969943)
>>>

But according to pip my installation is complete.

Any thoughts ?

Sarah Keating

**Comment by sebotic** [comment]
are you having more than one Python version installed, e.g. Py2 and Py3 on the same machine. What is the version of Wikidataintegrator you have installed? (pip show wikidataintegrator)

**Comment by stuppie** [comment]
I think you have an old version installed. Try `pip install wikidataintegrator -U`

**Comment by skeating** [comment]
Thanks an update worked. Sorry for the false alarm !
