### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by vrandezo** [SuLab/WikidataIntegrator#96]
Issue might easily be with the user.

Trying to install wikidataintegrator unfortunately fails with the following error message:

```
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-build-V1oBos/jsonasobj/setup.py", line 18, in <module>
import jsonasobj
File "/tmp/pip-build-V1oBos/jsonasobj/src/jsonasobj/init.py", line 1, in <module>
from jsonasobj.jsonobj import JsonObj, as_dict, as_list, as_json, as_json_obj, get, items, loads, load, setdefault
File "/tmp/pip-build-V1oBos/jsonasobj/src/jsonasobj/jsonobj.py", line 26
def _get(self, item: str, default: JsonObjTypes=None) -> JsonObjTypes:
^
SyntaxError: invalid syntax

----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-V1oBos/jsonasobj/
```

This was because I used the python 2.7 pip. I had to install python3-pip and then could install wikidataintegrator by using

`pip3 install wikidataintegrator`

Recommendation is to maybe update the documentation.

**Comment by andrawaag** [comment]
Thanks for reporting this. I will update the documentation.
